# Site settings
title: Dave Culligan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog website, following the life and adventures of David Culligan. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daveculligan.ca" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 8

# Build settings
markdown: kramdown

include: 
 - bower_components
